// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcU0U-ANwQ7OZSOdNSyEzV_r1RGgH-nfQ',
    appId: '1:936257092081:web:d83f107b124378db1f6c50',
    messagingSenderId: '936257092081',
    projectId: 'iot-smart-home-c9840',
    authDomain: 'iot-smart-home-c9840.firebaseapp.com',
    databaseURL: 'https://iot-smart-home-c9840-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-c9840.firebasestorage.app',
    measurementId: 'G-X79G2HJLDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_PLACEHOLDER',
    appId: '1:936257092081:android:af2af4e2ef829d671f6c50',
    messagingSenderId: '936257092081',
    projectId: 'iot-smart-home-c9840',
    databaseURL: 'https://iot-smart-home-c9840-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-c9840.firebasestorage.app',
  );
}
